name: Build Arch Linux KDE Live CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-livecd:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Arch Linux container
        run: |
          docker pull archlinux:latest
          docker run -d --name arch-builder --privileged \
            -v $PWD/livecd:/build/archiso-kde \
            archlinux:latest sleep infinity

          docker exec arch-builder pacman -Syu --noconfirm
          docker exec arch-builder pacman -S --noconfirm archiso git base-devel wget

      - name: Create archiso profile
        run: |
          docker exec arch-builder bash -c '
          cd /build/archiso-kde
          mkdir -p airootfs/root/Desktop
          rsync -a --ignore-existing /usr/share/archiso/configs/releng/ ./
          cp airootfs/etc/skel/Desktop/*.desktop airootfs/root/Desktop/
          chmod +x airootfs/usr/local/bin/arch-installer
          chmod +x airootfs/etc/skel/Desktop/*.desktop
          chmod +x airootfs/root/Desktop/*.desktop
          chmod +x airootfs/usr/local/bin/arch-installer
          chmod +x airootfs/usr/local/bin/livecd-loading
          chmod +x airootfs/root/customize_airootfs.sh
          '

      - name: Build ISO
        run: |
          docker exec arch-builder bash -c '
          cd /build/archiso-kde
          mkarchiso -v -w work -o out .
          '
          mkdir -p iso-output
          docker cp arch-builder:/build/archiso-kde/out/. ./iso-output/
          ls -lh ./iso-output/

      - name: Compress ISO with xz
        run: |
          sudo apt-get update && sudo apt-get install -y xz-utils
          for iso in iso-output/*.iso; do
            xz -z -T0 -9 "$iso"
          done
          ls -lh ./iso-output/

      - name: Cleanup
        if: always()
        run: |
          docker stop arch-builder || true
          docker rm arch-builder || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: arch-kde-livecd
          path: iso-output/*.iso.xz
          retention-days: 30

      - name: Create Release
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Arch Linux KDE Live CD v${{ github.run_number }}
          body: |
            # 🐧 Arch Linux KDE Live CD
          files: iso-output/*.iso.xz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
