name: Build Custom Arch ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_iso:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux

      - name: Install archiso
        run: |
          pacman -Sy --noconfirm archiso

      - name: Build Arch ISO
        run: |
          rm -rf /tmp/archiso-work out
          mkarchiso -v -w /tmp/archiso-work -o out archiso-releng

      - name: Upload ISO as action artifact
        uses: actions/upload-artifact@v3
        with:
          name: custom-archlinux.iso
          path: out/*.iso

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: "Arch Linux Custom ISO v${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Upload ISO to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: out/*.iso
          asset_name: custom-archlinux.iso
          asset_content_type: application/octet-stream
